tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "awscli"
brew "docker"
brew "docker-compose"
brew "imagemagick"
brew "rbenv"
brew "starship"
brew "yarn"
brew "heroku/brew/heroku"

########
# Casks
########
cask "coteditor"
cask "db-browser-for-sqlite"
cask "docker"
cask "font-source-han-code-jp"
cask "github"
cask "google-chrome"
cask "lunar"
cask "mos"
cask "slack"
cask "visual-studio-code"
